name: Release

# Triggered only when a tag is pushed
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
        id: go

      - name: Release the library
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
